- name: Install {{ COMPONENT }}
  ansible.builtin.dnf:
    name: mongodb-org
    state: latest

- name: Copying the repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Replacing loopback a string in a file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    backup: yes      

- name: Restarting "{{COMPONENT}}" 
  ansible.builtin.systemd_service:
    name: mongod
    state: started             #DB's not meant to be restarted all the time
    enabled: true
    daemon_reload: true