- name: Enabling 1.24 of nginx
  ansible.builtin.shell: dnf module disable nginx -y ; dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Cleanup old content
  ansible.builtin.file:
   path: /usr/share/nginx/html
   state: absent
  ignore_errors: true  # optional, in case it doesn't exist   


- name: Copy file with owner and permissions
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

# - name: App Pre-requisite Tasks
#   ansible.builtin.include_role:           # through this we can call any role inside another role
#     name: common                          # Name of the role to be called
#     tasks_from: pre-req                   # Name of the file to be called inside the role  

- name: Create a App Directory
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: directory

- name: Downloading & unarchiving the "{{COMPONENT}}" Code
  ansible.builtin.unarchive:
    src: "{{ URL }}"
    dest: "{{APP_PATH}}"
    remote_src: yes

- name: Restarting "{{COMPONENT}}" 
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true
    daemon_reload: true