- name: Installing Python 3
  ansible.builtin.dnf:
    name:
     - python3
     - gcc
     - python3-devel
    state: latest

- name: Create user & app directory
  ansible.builtin.include_role:
    name: common
    tasks_from: user-and-app-dir

- name: Downloading the dependencies for app
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
   chdir: "{{ APP_PATH }}"

- name: Configuring {{COMPONENT}} systemd
  ansible.builtin.template:
    src: "{{COMPONENT}}.service"
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restarting {{COMPONENT}}
  ansible.builtin.systemd_service:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Configuring hostname
  ansible.builtin.shell: set-hostname {{ COMPONENT }}-{{ ENV }}    